apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
# replicases just mean number of copy
  replicas: 1   
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: anshuvermaa/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv


# here we do not need any service because this service at all not contacted by any other service

